#!/bin/sh

cmd=$(printf "Danish\nEnglish\nColemak\n" | dmenu -nf "#d3d0c8" -nb "#2d2d2d" -sf "#d3d0c8" -sb "#747369" $*)

if [ -z "$cmd" ]; then
	exit 0
fi

case "$cmd" in
	Danish)
		setxkbmap dk ;;
	English)
		setxkbmap us;;
	Colemak)
		setxkbmap us colemak && xmodmap ~/.Xmodmap;;
	*)
		printf "Option not recognized: %s\n" "$cmd" >&2
esac
