#!/bin/bash

. "/home/vuoto/.cache/wal/colors.sh"

FG=$color7
BG=$color0
SB=$color8
SF=$color7

QUERY=$(cat ~/.cache/define_history | rofi -dmenu)
if [ -n "$QUERY" ]; then
    grep -q "$QUERY" "$HOME/.cache/define_history"
    echo $QUERY >> ~/.cache/define_history_temp && sort -u ~/.cache/define_history_temp > ~/.cache/define_history
    st -e sh -c "sdcv $QUERY | less"
fi
